// Code generated by MockGen. DO NOT EDIT.
// Source: castai-agent/internal/services/version (interfaces: Interface)

// Package mock_version is a generated GoMock package.
package mock_version

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Full mocks base method.
func (m *MockInterface) Full() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Full")
	ret0, _ := ret[0].(string)
	return ret0
}

// Full indicates an expected call of Full.
func (mr *MockInterfaceMockRecorder) Full() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Full", reflect.TypeOf((*MockInterface)(nil).Full))
}

// MinorInt mocks base method.
func (m *MockInterface) MinorInt() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinorInt")
	ret0, _ := ret[0].(int)
	return ret0
}

// MinorInt indicates an expected call of MinorInt.
func (mr *MockInterfaceMockRecorder) MinorInt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinorInt", reflect.TypeOf((*MockInterface)(nil).MinorInt))
}
