version: "2"
linters:
  default: none
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - mock
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(castai-agent)
  exclusions:
    generated: lax
    paths:
      - mock
      - third_party$
      - builtin$
      - examples$
