// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package aws

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ec2/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetAccountID provides a mock function for the type MockClient
func (_mock *MockClient) GetAccountID(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountID")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountID'
type MockClient_GetAccountID_Call struct {
	*mock.Call
}

// GetAccountID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetAccountID(ctx interface{}) *MockClient_GetAccountID_Call {
	return &MockClient_GetAccountID_Call{Call: _e.mock.On("GetAccountID", ctx)}
}

func (_c *MockClient_GetAccountID_Call) Run(run func(ctx context.Context)) *MockClient_GetAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetAccountID_Call) Return(s *string, err error) *MockClient_GetAccountID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetAccountID_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *MockClient_GetAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterName provides a mock function for the type MockClient
func (_mock *MockClient) GetClusterName(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterName")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetClusterName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterName'
type MockClient_GetClusterName_Call struct {
	*mock.Call
}

// GetClusterName is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetClusterName(ctx interface{}) *MockClient_GetClusterName_Call {
	return &MockClient_GetClusterName_Call{Call: _e.mock.On("GetClusterName", ctx)}
}

func (_c *MockClient_GetClusterName_Call) Run(run func(ctx context.Context)) *MockClient_GetClusterName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetClusterName_Call) Return(s *string, err error) *MockClient_GetClusterName_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetClusterName_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *MockClient_GetClusterName_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstancesByInstanceIDs provides a mock function for the type MockClient
func (_mock *MockClient) GetInstancesByInstanceIDs(ctx context.Context, instanceIDs []string) ([]types.Instance, error) {
	ret := _mock.Called(ctx, instanceIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetInstancesByInstanceIDs")
	}

	var r0 []types.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]types.Instance, error)); ok {
		return returnFunc(ctx, instanceIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []types.Instance); ok {
		r0 = returnFunc(ctx, instanceIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, instanceIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetInstancesByInstanceIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstancesByInstanceIDs'
type MockClient_GetInstancesByInstanceIDs_Call struct {
	*mock.Call
}

// GetInstancesByInstanceIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceIDs []string
func (_e *MockClient_Expecter) GetInstancesByInstanceIDs(ctx interface{}, instanceIDs interface{}) *MockClient_GetInstancesByInstanceIDs_Call {
	return &MockClient_GetInstancesByInstanceIDs_Call{Call: _e.mock.On("GetInstancesByInstanceIDs", ctx, instanceIDs)}
}

func (_c *MockClient_GetInstancesByInstanceIDs_Call) Run(run func(ctx context.Context, instanceIDs []string)) *MockClient_GetInstancesByInstanceIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetInstancesByInstanceIDs_Call) Return(instances []types.Instance, err error) *MockClient_GetInstancesByInstanceIDs_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockClient_GetInstancesByInstanceIDs_Call) RunAndReturn(run func(ctx context.Context, instanceIDs []string) ([]types.Instance, error)) *MockClient_GetInstancesByInstanceIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegion provides a mock function for the type MockClient
func (_mock *MockClient) GetRegion(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRegion")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegion'
type MockClient_GetRegion_Call struct {
	*mock.Call
}

// GetRegion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetRegion(ctx interface{}) *MockClient_GetRegion_Call {
	return &MockClient_GetRegion_Call{Call: _e.mock.On("GetRegion", ctx)}
}

func (_c *MockClient_GetRegion_Call) Run(run func(ctx context.Context)) *MockClient_GetRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetRegion_Call) Return(s *string, err error) *MockClient_GetRegion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetRegion_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *MockClient_GetRegion_Call {
	_c.Call.Return(run)
	return _c
}
